import { Vehicle, Booking, Review } from "./types";

export const vehicles: Vehicle[] = [
  {
    id: "v1",
    name: "Swift Dzire",
    brand: "Maruti Suzuki",
    model: "Dzire VXi",
    year: 2024,
    type: "SEDAN",
    fuelType: "PETROL",
    transmission: "MANUAL",
    seats: 5,
    pricePerHour: 150,
    pricePerDay: 1800,
    images: [
      "https://images.unsplash.com/photo-1549924231-f129b911e442?w=800&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
    ],
    description:
      "The Maruti Suzuki Dzire is a compact sedan perfect for city commutes and short trips around Delhi NCR. Fuel-efficient and comfortable.",
    features: ["AC", "Power Steering", "Bluetooth", "USB Charging", "Airbags"],
    available: true,
    location: "Connaught Place, Delhi",
    licensePlate: "DL01AB1234",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "v2",
    name: "Hyundai Creta",
    brand: "Hyundai",
    model: "Creta SX(O)",
    year: 2024,
    type: "SUV",
    fuelType: "DIESEL",
    transmission: "AUTOMATIC",
    seats: 5,
    pricePerHour: 250,
    pricePerDay: 3000,
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
    ],
    description:
      "The Hyundai Creta is a premium compact SUV with top-notch features, sunroof, and a powerful diesel engine. Ideal for highway drives and weekend getaways.",
    features: [
      "Panoramic Sunroof",
      "Ventilated Seats",
      "360 Camera",
      "Wireless Charging",
      "ADAS",
      "Cruise Control",
    ],
    available: true,
    location: "Gurugram, Haryana",
    licensePlate: "HR26DK5678",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "v3",
    name: "Toyota Fortuner",
    brand: "Toyota",
    model: "Fortuner 4x4 AT",
    year: 2023,
    type: "SUV",
    fuelType: "DIESEL",
    transmission: "AUTOMATIC",
    seats: 7,
    pricePerHour: 450,
    pricePerDay: 5500,
    images: [
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80",
    ],
    description:
      "The Toyota Fortuner is a full-size SUV built for commanding road presence and off-road capability. Perfect for group travel and long journeys.",
    features: [
      "4x4 Drive",
      "Leather Seats",
      "Touchscreen Infotainment",
      "Rear AC",
      "Hill Assist",
      "6 Airbags",
    ],
    available: true,
    location: "Aerocity, Delhi",
    licensePlate: "DL03CJ9012",
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "v4",
    name: "Honda City",
    brand: "Honda",
    model: "City ZX CVT",
    year: 2024,
    type: "SEDAN",
    fuelType: "PETROL",
    transmission: "AUTOMATIC",
    seats: 5,
    pricePerHour: 200,
    pricePerDay: 2400,
    images: [
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80",
      "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80",
    ],
    description:
      "The Honda City is a premium sedan with a refined CVT gearbox, Honda SENSING safety suite, and best-in-class boot space.",
    features: [
      "Honda SENSING",
      "Lane Keep Assist",
      "Sunroof",
      "Wireless CarPlay",
      "LED Headlamps",
    ],
    available: true,
    location: "Noida, UP",
    licensePlate: "UP16EF3456",
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "v5",
    name: "Maruti Baleno",
    brand: "Maruti Suzuki",
    model: "Baleno Alpha",
    year: 2024,
    type: "HATCHBACK",
    fuelType: "PETROL",
    transmission: "MANUAL",
    seats: 5,
    pricePerHour: 120,
    pricePerDay: 1400,
    images: [
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80",
    ],
    description:
      "The Baleno is a feature-packed premium hatchback. Great mileage, spacious interiors, and perfect for navigating Delhi traffic.",
    features: [
      "Heads-Up Display",
      "360 View Camera",
      "Smartplay Pro+",
      "6 Airbags",
      "Auto AC",
    ],
    available: true,
    location: "Dwarka, Delhi",
    licensePlate: "DL08GH7890",
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "v6",
    name: "Mercedes-Benz E-Class",
    brand: "Mercedes-Benz",
    model: "E 200 Expression",
    year: 2023,
    type: "LUXURY",
    fuelType: "PETROL",
    transmission: "AUTOMATIC",
    seats: 5,
    pricePerHour: 800,
    pricePerDay: 9500,
    images: [
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
      "https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80",
    ],
    description:
      "The Mercedes-Benz E-Class is the epitome of luxury and sophistication. Perfect for business travel, weddings, and premium experiences.",
    features: [
      "MBUX Infotainment",
      "Burmester Sound",
      "Ambient Lighting",
      "Massage Seats",
      "Air Suspension",
      "9G-Tronic",
    ],
    available: true,
    location: "Aerocity, Delhi",
    licensePlate: "DL01CD2345",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "v7",
    name: "Toyota Innova Crysta",
    brand: "Toyota",
    model: "Innova Crysta GX",
    year: 2024,
    type: "MUV",
    fuelType: "DIESEL",
    transmission: "MANUAL",
    seats: 7,
    pricePerHour: 300,
    pricePerDay: 3500,
    images: [
      "https://images.unsplash.com/photo-1606611013016-969c19ba27d5?w=800&q=80",
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80",
    ],
    description:
      "The Innova Crysta is India's favourite MPV — spacious, reliable, and comfortable for family trips and group travel.",
    features: [
      "Captain Seats",
      "Rear AC",
      "Touchscreen",
      "Cruise Control",
      "7 Airbags",
      "Roof Rails",
    ],
    available: true,
    location: "Karol Bagh, Delhi",
    licensePlate: "DL05IJ6789",
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2024-03-10T00:00:00Z",
  },
  {
    id: "v8",
    name: "Tata Nexon EV",
    brand: "Tata",
    model: "Nexon EV Max LR",
    year: 2024,
    type: "SUV",
    fuelType: "ELECTRIC",
    transmission: "AUTOMATIC",
    seats: 5,
    pricePerHour: 220,
    pricePerDay: 2600,
    images: [
      "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80",
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80",
    ],
    description:
      "Go green with the Tata Nexon EV Max. With 437km range and fast charging, it's the perfect electric SUV for eco-conscious drivers.",
    features: [
      "437km Range",
      "Fast Charging",
      "Connected Car Tech",
      "Ventilated Seats",
      "Sunroof",
      "6 Airbags",
    ],
    available: true,
    location: "Greater Noida, UP",
    licensePlate: "UP16KL0123",
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-04-01T00:00:00Z",
  },
];

export const testimonials = [
  {
    id: "t1",
    name: "Rahul Sharma",
    role: "Business Traveler",
    content:
      "RydeX made my Delhi business trip so easy. Booked a Honda City in minutes, and the car was spotless. Will definitely use again!",
    rating: 5,
    avatar: "RS",
  },
  {
    id: "t2",
    name: "Priya Gupta",
    role: "Weekend Explorer",
    content:
      "Took a Creta for a weekend trip to Jaipur. Smooth booking process, great car condition, and very affordable pricing.",
    rating: 5,
    avatar: "PG",
  },
  {
    id: "t3",
    name: "Amit Verma",
    role: "Family Traveler",
    content:
      "Rented an Innova for a family trip to Agra. The car was clean, well-maintained, and the whole experience was hassle-free.",
    rating: 4,
    avatar: "AV",
  },
  {
    id: "t4",
    name: "Sneha Reddy",
    role: "Corporate Client",
    content:
      "We use RydeX for all our corporate travel needs in Delhi NCR. Professional service, premium cars, and competitive rates.",
    rating: 5,
    avatar: "SR",
  },
];

export const stats = [
  { label: "Happy Customers", value: "5,000+" },
  { label: "Vehicles Available", value: "150+" },
  { label: "Cities Covered", value: "10+" },
  { label: "Rides Completed", value: "25,000+" },
];

export const howItWorks = [
  {
    step: 1,
    title: "Choose Your Car",
    description:
      "Browse our wide selection of well-maintained vehicles and pick the one that suits your needs.",
  },
  {
    step: 2,
    title: "Book & Pay",
    description:
      "Select your dates, pickup location, and complete the booking with our secure payment system.",
  },
  {
    step: 3,
    title: "Hit the Road",
    description:
      "Pick up your car at the chosen location and enjoy your drive. Return it when you're done!",
  },
];
